// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Song struct {
	ID     string   `json:"id" bson:"_id"`
	Title  *string  `json:"title,omitempty"`
	Lyrics []*Lyric `json:"lyrics"`
}

type NewSong struct {
	Title string
}
